version: '3.8'

services:
  java-maven-app:
    # If you want latest image
    # image: ismailsdockers/java-maven-app:latest
    # If you want to specify dynamically
    image: ${IMAGE}
    ports:
      - 8080:8080
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password